version: '3.9'
services:
  node:
    container_name: ma_super_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: ma_super_app_db
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./certs:/certs

  mysql:
    image: mysql:latest
    container_name: ma_super_app_mysql
    environment:
      MYSQL_DATABASE: ma_super_app_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local